# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx5G
org.gradle.parallel=true

# Mod properties
mod_version=0.0.0.4
maven_group=com.github.skillfi.tensura_mf
archives_name=tensura_mf
enabled_platforms=neoforge
mod_display_name = TenSura More Features
lombok.addLombokGeneratedAnnotation = true

# Minecraft properties
minecraft_version=1.21.1

# Dependencies
architectury_api_version=13.0.8
fabric_loader_version=0.16.10
fabric_api_version=0.115.0+1.21.1
neoforge_version=21.1.216

#CurseForge (TenSura)
tensura_neoforge_file_id=8665599
tensura_common_file_id=8665600
tensura_fabric_file_id=8665595

#CurseForge (ManasCore)
manasCore_neoforge_file_id=7869418
manasCore_common_file_id=8665600
manasCore_fabric_file_id=7869424

manasCoreVersion = 4.0.0.1
geckolib_version= 4.7.5
sbl_version= 1.16.7
terrablender_version= 4.1.0.0

jei_version=19.22.0.315
fabric_permissions_api_version=0.3.1
fabric_luckperms_version=v5.4.140-fabric
